@SudokuObservable.Api_HostAddress = http://localhost:5224

GET {{SudokuObservable.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

# @name createGame
POST {{SudokuObservable.Api_HostAddress}}/games
Accept: application/json

###

@gameId = {{createGame.response.body.$.id}}

GET {{SudokuObservable.Api_HostAddress}}/games/{{gameId}}
Accept: application/json

###

GET {{SudokuObservable.Api_HostAddress}}/games/{{gameId}}/cells/5/5/candidates
Accept: application/json

###
